### ISSUE TITLE
Webpack + Autodesk360App.js and viewer3D

### ISSUE THREAD

**Issue by duhaime** [Developer-Autodesk/ng-gallery#7]
Hi, I'm loving the Autodesk API. I have a live app that I want to optimize for mobile (!), and I therefore want to compile the Autodesk360App and viewer3D source into my webpack bundle. 

Is it possible to `npm install` these assets so I can require them in CommonJS fashion? If not, are there examples of folks using `require('');` on each of the two files above for bundling purposes? 

I'd be grateful for any insights you can offer on this thread.

**Comment by cyrillef** [comment]
Hi
I wrote an example here: https://github.com/cyrillef/Pier9.IoT using require.js
but one of my colleague has experiences with webpack. I'll let him know about your question.
Now would you mind asking your question about compiling source in your bundle at forge.help@autodesk.com?
-cyrille

**Comment by duhaime** [comment]
Thanks so much @cyrillef -- I just sent an email to that address to follow up. Any help your team can provide would be great!

**Comment by leefsmp** [comment]
Unfortunately I doubt that Cyrille's example is what you are looking for, he is using requirejs, but not 'require(...)' in the webpack way to bundle static assets and libs into a single chunk. The code will still fetch the viewer API script from Autodesk servers at runtime.

I have extensively used webpack for over the various samples I wrote for the viewer, however we do not an npm or similar package for the client side API. In your application html, you are referencing a single .js for the viewer API, but when loaded, the viewer code will fetch other scripts and resources as needed relative to the "viewer3D.js" (or "viewer3D.min.js"). You can however grab all the required assets "manually" (I recall Cyrille has mentioned an hidden script for that ;)) and run the viewer locally or serve those files from a route in your app. You could theoretically modify the source code to suppress the http requests and load all required assets statically so they could be bundled but that would required some work from your side.
[https://github.com/Autodesk-Forge/forge-boilers.nodejs/tree/master/1%20-%20viewer-offline/viewer-lib](https://github.com/Autodesk-Forge/forge-boilers.nodejs/tree/master/1%20-%20viewer-offline/viewer-lib)

I'm not sure about plans from the dev team to provide a bundable package but that would definitely be a nice thing to have.

Please in the feature use stackoverflow with tags "forge-viewer" to ask related questions, this is not an issue for that repo.

Thanks

**Comment by duhaime** [comment]
Thanks @leefsmp, this is helpful. I wasn't sure how closely the SO boards are watched, or if I should write your team's support address with questions, but I thought someone working on Node projects with Autodesk might have some insight into commonJS approaches to bundling these assets. In any event, I'm glad to have this question resolved for the moment--thanks for following up!
